[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'python3', 'gcc', 'make']

[phases.install]
cmds = [
  'yarn install --ignore-optional',
  'cd frontend && yarn install --ignore-optional',
  'cd ../bitquery && yarn install --ignore-optional',
  'cd ../elizaos-agents && yarn install --ignore-optional',
  'cd ../js-scraper && yarn install --ignore-optional'
]

[phases.build]
cmds = ['cd frontend && yarn build']

[start]
cmd = 'node railway-start.js'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_SKIP_DOWNLOAD = 'true'
NODE_OPTIONS = '--max-old-space-size=1024'
npm_config_build_from_source = 'false'
npm_config_cache = '/tmp/.npm'
npm_config_optional = 'false'
