[phases.setup]
nixPkgs = ['nodejs_18', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = [
  'cd frontend && yarn install --frozen-lockfile',
  'cd frontend && yarn build',
  'cd elizaos-agents && yarn install --frozen-lockfile'
]

[start]
cmd = 'npm run start:railway'
