[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = [
  'yarn install --frozen-lockfile',
  'cd frontend && yarn install --frozen-lockfile',
  'cd ../bitquery && yarn install --frozen-lockfile',
  'cd ../elizaos-agents && yarn install --frozen-lockfile',
  'cd ../js-scraper && yarn install --frozen-lockfile --ignore-optional'
]

[phases.build]
cmds = ['cd frontend && yarn build']

[start]
cmd = 'node railway-start.js'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_SKIP_DOWNLOAD = 'true'
