services:
  - type: web
    name: wojat-platform
    env: node
    plan: starter
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_WS_URL
        value: wss://wojat-platform.onrender.com/ws
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: main
