# Render.com deployment configuration for Wojat Platform
# This file is optional but provides better control over deployment

services:
  - type: web
    name: wojat-platform
    env: node
    plan: starter
    buildCommand: |
      npm install --legacy-peer-deps
      cd frontend && npm install --legacy-peer-deps && NODE_ENV=production npm run build
      cd ../elizaos-agents && npm install --legacy-peer-deps
      cd ../js-scraper && npm install --legacy-peer-deps
      cd ../bitquery && npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      # Add your environment variables here
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: BITQUERY_API_KEY
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: CONSUMER_KEY
        sync: false
      - key: CONSUMER_SECRET
        sync: false
      - key: ZORO_ACCESS_TOKEN
        sync: false
      - key: ZORO_ACCESS_TOKEN_SECRET
        sync: false
      - key: SOLANA_PRIVATE_KEY
        sync: false
      - key: SOLANA_PUBLIC_KEY
        sync: false
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
